In [1]:
import os

In [2]:
os.chdir("C:\\Users\\sanky45\\Downloads")

In [3]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
import pickle

In [4]:
data = pd.read_csv("Churn_Modelling.csv")

In [5]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
data = data.drop(["RowNumber","CustomerId","Surname"],axis=1) 
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
label_enco_gender = LabelEncoder()
data['Gender']=label_enco_gender.fit_transform(data['Gender'])

In [8]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [9]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[["Geography"]])
geo_encoder

<10000x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in Compressed Sparse Row format>

In [10]:
features = onehot_encoder_geo.get_feature_names_out(["Geography"])

In [11]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [12]:
geo_encoder_df = pd.DataFrame(geo_encoder.toarray(),columns = features)

In [13]:
geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [14]:
data = pd.concat([data.drop("Geography",axis = 1),geo_encoder_df],axis=1)

In [15]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [16]:
with open('label_enco_gender.pkl','wb') as file :
    pickle.dump(label_enco_gender,file)
    
with open('onehot_encoder_geo.pkl','wb') as file :
    pickle.dump(onehot_encoder_geo,file)

In [17]:
X = data.drop('Exited',axis = 1)
y = data['Exited']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [19]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [20]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [23]:
pip install protobuf==3.20.*

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Collecting protobuf==3.20.*
  Downloading protobuf-3.20.3-cp39-cp39-win_amd64.whl (904 kB)
     ------------------------------------ 904.2/904.2 kB 200.7 kB/s eta 0:00:00
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.28.2
    Uninstalling protobuf-5.28.2:
      Successfully uninstalled protobuf-5.28.2

WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\sanky45\\AppData\\Roaming\\Python\\Python39\\site-packages\\google\\~~pb\\_message.cp39-win_amd64.pyd'
Check the permissions.

WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)

In [24]:
#ANN IMPLIMENTATION

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

In [116]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
]
)

In [117]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 64)                832

 dense_7 (Dense)             (None, 32)                2080

 dense_8 (Dense)             (None, 1)                 33

=================================================================
Total params: 2,945
Trainable params: 2,945
Non-trainable params: 0
_________________________________________________________________

In [118]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics = ["accuracy"])

In [119]:
#Set up the tensorboard
log_dir= "logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [120]:
#SET UP EARLY STOPPING

early_stopping_callback = EarlyStopping(monitor="val_loss",patience=5,restore_best_weights=True)

In [121]:
history = model.fit(X_train,y_train,validation_data=(X_test,y_test),callbacks = (tensorflow_callback,early_stopping_callback),epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4518 - accuracy: 0.8011 - val_loss: 0.3912 - val_accuracy: 0.8325
Epoch 2/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3821 - accuracy: 0.8430 - val_loss: 0.3637 - val_accuracy: 0.8480
Epoch 3/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3557 - accuracy: 0.8550 - val_loss: 0.3464 - val_accuracy: 0.8560
Epoch 4/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3457 - accuracy: 0.8589 - val_loss: 0.3423 - val_accuracy: 0.8600
Epoch 5/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3402 - accuracy: 0.8591 - val_loss: 0.3422 - val_accuracy: 0.8605
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3362 - accuracy: 0.8627 - val_loss: 0.3455 - val_accuracy: 0.8605
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3326 - accuracy: 0.8637 - val_loss: 0.3396 - val_accuracy: 0.8670
Epoch 8/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3306 - accuracy: 0.8652 - val_loss: 0.3384 - val_accuracy: 0.8615
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3279 - accuracy: 0.8646 - val_loss: 0.3426 - val_accuracy: 0.8580
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3260 - accuracy: 0.8673 - val_loss: 0.3375 - val_accuracy: 0.8690
Epoch 11/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3229 - accuracy: 0.8669 - val_loss: 0.3427 - val_accuracy: 0.8625
Epoch 12/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3202 - accuracy: 0.8664 - val_loss: 0.3445 - val_accuracy: 0.8635
Epoch 13/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3184 - accuracy: 0.8698 - val_loss: 0.3393 - val_accuracy: 0.8620
Epoch 14/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3178 - accuracy: 0.8702 - val_loss: 0.3405 - val_accuracy: 0.8620
Epoch 15/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3168 - accuracy: 0.8681 - val_loss: 0.3388 - val_accuracy: 0.8605

In [122]:
model.save('model.h5')

In [123]:
pip install tensorboard

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tensorboard in c:\users\sanky45\appdata\roaming\python\python39\site-packages (2.10.1)
Requirement already satisfied: wheel>=0.26 in c:\programdata\anaconda3\lib\site-packages (from tensorboard) (0.37.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from tensorboard) (2.13.0)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from tensorboard) (3.0.3)
Requirement already satisfied: markdown>=2.6.8 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from tensorboard) (3.4.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from tensorboard) (70.2.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from tensorboard) (0.4.6)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from tensorboard) (3.19.6)
Requirement already satisfied: grpcio>=1.24.3 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from tensorboard) (1.49.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\programdata\anaconda3\lib\site-packages (from tensorboard) (2.28.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from tensorboard) (0.6.1)
Requirement already satisfied: numpy>=1.12.0 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from tensorboard) (1.23.4)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from tensorboard) (1.8.1)
Requirement already satisfied: absl-py>=0.4 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from tensorboard) (1.3.0)
Requirement already satisfied: six>=1.9.0 in c:\programdata\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard) (1.16.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from google-auth<3,>=1.6.3->tensorboard) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from google-auth<3,>=1.6.3->tensorboard) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from google-auth<3,>=1.6.3->tensorboard) (5.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from markdown>=2.6.8->tensorboard) (5.0.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from requests<3,>=2.21.0->tensorboard) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard) (2022.9.24)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard) (1.26.11)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from werkzeug>=1.0.1->tensorboard) (2.1.5)
Requirement already satisfied: zipp>=0.5 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard) (3.9.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\sanky45\appdata\roaming\python\python39\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard) (3.2.1)

WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\sanky45\appdata\roaming\python\python39\site-packages)

In [124]:
##load the tensorboard
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [125]:
%tensorboard --logdir logs/fit20240922-212157

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [126]:
#LETS USE PICKLE FILE FOR PREDICTION

from tensorflow.keras.models import load_model
import numpy as np

In [127]:
#LOAD TRAIN MODEL,SCALER FILE,OMNEHOT ENCODING FILE

model = load_model('model.h5')

#LOAD ENCODER AND SCALER AND OHE
with open('label_enco_gender.pkl','rb') as file:
    label_enco_gender = pickle.load(file)
    
with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)
    
with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo = pickle.load(file)

In [128]:
#example input data

input_data ={
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age' : 40,
    'Tenure': 3,
    'Balance' : 60000,
    'NumOfProducts': 2,
    'HasCrCard':1,
    'IsActiveMember': 1,
    'EstimatedSalary':50000
}

In [129]:
#One hot encode Geography

geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

C:\Users\sanky45\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [130]:
input_data = pd.DataFrame([input_data])

In [131]:
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [132]:
#ENCODE CATEGORICAL VAAIABLE GENDER
input_data['Gender'] = label_enco_gender.transform(input_data['Gender'])
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [133]:
input_data_df = pd.concat([input_data.reset_index(drop=True),geo_encoded_df],axis=1)

In [134]:
input_data_df = input_data_df.drop(['Geography'],axis=1)

In [135]:
input_data_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [136]:
#INPUT THE SCALING DATA
input_scaled = scaler.transform(input_data_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [138]:
prediction = model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 62ms/step

array([[0.03110096]], dtype=float32)

In [141]:
prediction_proba = prediction[0][0]
prediction_proba

0.03110096

In [142]:
if prediction_proba > 0.5:
    print("the customer is likely to churn")
else:
    print("the customer is not likely to churn")

the customer is not likely to churn